language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install:
- echo $encrypted_d97f125b9303_key
- echo $encrypted_d97f125b9303_iv
- openssl aes-256-cbc -K $encrypted_d97f125b9303_key -iv $encrypted_d97f125b9303_iv -in .travis/r.key.enc -out .travis/r.key -d
before_script:
  - echo -e "Host *.cloudapp.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- test $TRAVIS_BRANCH != "develop"
  && gulp build && cp package.json dist/package.json
  && cp bower.json dist/bower.json
  && cd dist
  && npm install --production
  && cd $TRAVIS_BUILD_DIR
  && tar -zcvf tg-$TRAVIS_BRANCH.tar.gz dist && export PRODBUILDCOMPLETE=true
- test $TRAVIS_BRANCH == "develop" && echo "on develop"
  && chmod 600 .travis/regex.azure.key
  && eval $(ssh-agent)
  && ssh-add .travis/regex.azure.key
  && git remote add deploy-server tg@regex-test.cloudapp.net:/home/tg/travis-test.git
  && git push --force deploy-server $TRAVIS_BRANCH:master
deploy:
  provider: releases
  api_key:
    secure: dYl992DRXkR0JKRxyFQy+AYFcVzbLi6+DnSVu+Ht6in0/ddb+MO+rCZc8YSNTQmky1gFPzEcv9LMxo+mdrjLrFN7sUY8KeysAWedeb/mCrixdyELwdy5hSR/fZTqFXoJUWon3HPybenhrUwsG6FcAXlKzDPCjdHGKjHgjibUzfI=
  file: tg-$TRAVIS_BRANCH.tar.gz
  on:
    condition: $PRODBUILDCOMPLETE = true
    repo: tgrrtt/travis-test
    all_branches: true
    tags: true
