language: node_js
node_js:
- '0.10'
notifications:
  email: false

before_install:
- export YOLO=true
- export YOLO2="true"
- echo "before install"
- test $YOLO && echo "first YOLO CASE PASS"
# - [[ $YOLO ]] && echo "3RD YOLO CASE"
- test $SWAG
- echo "first swag case true"
install:
- echo "install"
before_script:
- echo "befor script"
script:
- echo "script"
after_success:
- echo "after success"
after_failure:
- echo "after_failusre"
after_script:
- echo "after script"
before_deploy:
- echo "before deploy"
deploy:
  provider: releases
  api_key:
    secure: dYl992DRXkR0JKRxyFQy+AYFcVzbLi6+DnSVu+Ht6in0/ddb+MO+rCZc8YSNTQmky1gFPzEcv9LMxo+mdrjLrFN7sUY8KeysAWedeb/mCrixdyELwdy5hSR/fZTqFXoJUWon3HPybenhrUwsG6FcAXlKzDPCjdHGKjHgjibUzfI=
  file: tg-$TRAVIS_BRANCH.tar.gz
  on:
    repo: tgrrtt/travis-test
    all_branches: true
    tags: true
after_deploy:
- echo "after deploy"
